name: Release and Publish Eduva API

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - name: Release with release-please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

  publish:
    name: Publish Eduva API Docker Image
    needs: release
    if: ${{ needs.release.outputs.release_created == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.32.0
        with:
          image-ref: "eduva-api:${{ needs.release.outputs.tag_name }}"
          format: "sarif"
          output: "trivy-results.sarif"
          exit-code: "1" # Fail the job if vulnerabilities are found
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "HIGH,CRITICAL"

      - name: Upload Trivy scan results to GitHub Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "trivy-results.sarif"

      - name: Push Docker Image
        if: success()
        run: |
          cp ./backend/src/Eduva.API/Dockerfile .
          VERSION=${{ needs.release.outputs.tag_name }}
          echo "Using version $VERSION"
          docker buildx build . \
            --tag ghcr.io/${{ github.repository_owner }}/eduva-api:$VERSION \
            --tag ghcr.io/${{ github.repository_owner }}/eduva-api:latest \
            --platform=linux/amd64 \
            --push
